name: amount_input_formatter
description: "A minimalistic and configurable number formatter to use with the TextField widget."
version: 0.2.0
repository: https://github.com/TBR-Group-software/amount_input_formatter
issue_tracker: https://github.com/TBR-Group-software/amount_input_formatter/issues?q=is%3Aissue%20state%3Aopen%20

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

screenshots:
  - description: 'This screenshot shows the result example of usage of the package'
    path: assets/screenshots/example.png

topics:
  - formatter
  - util
  - string

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0
