name: amount_input_formatter
description: "A new Flutter package project."
version: 0.0.1
repository: https://github.com/TBR-Group-software/amount_input_formatter
issue_tracker: https://github.com/TBR-Group-software/amount_input_formatter/issues

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
